services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    command: ['python', 'main.py']

  frontend:
    build: ./frontend
    ports:
      - '8081:8081'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']